[file:$ROSE_DATA/etc/ancil/qrclim.sea]
source=/data/d06/marc.stringer/ancils/atmos/ukesm1.1/n96e/medusa/clims/by791/CHL/CHL_clim_by791_1979_2014_n96.anc

[file:$ROSE_DATA/etc/ancil/qrclim.sulpdms]
source=/data/d06/marc.stringer/ancils/atmos/ukesm1.1/n96e/medusa/clims/by791/DMS/DMS_clim_by791_1979_2014_n96.anc

[file:$ROSE_DATA/etc/ancil/qrparm.veg.canopy]
source=/data/d06/marc.stringer/ancils/atmos/ukesm2/n96e/vegetation/u-by791/u-by791_m01s00i218_1979-2014_time_mean_canopy_height.anc

[file:$ROSE_DATA/etc/ancil/qrparm.veg.frac]
source=/data/d06/marc.stringer/ancils/atmos/ukesm2/n96e/vegetation/u-by791/u-by791_m01s00i216_1979-2014_annual_timeseries_land_cover_frac.anc

[file:$ROSE_DATA/etc/ancil/qrparm.veg.lai]
source=/data/d06/marc.stringer/ancils/atmos/ukesm2/n96e/vegetation/u-by791/u-by791_m01s00i217_1979-2014_monthly_climatology_LAI.anc
