[file:ana/mule_cumf.py]
source=fcm:um.xm_tr/rose-stem/ana/mule_cumf.py@vn13.6

[template variables]
ARCHER2_GROUP='n02-TERRAFIRMA'
ARCHER2_QUEUE='standard'
ARCHER2_USERNAME='tetts'
BASIS=2010,9,1,0,0,0
BITCOMP_NRUN=false
!!CORE_EX='milan'
!!CORE_XC40='broadwell'
DATAM='History_Data'
EXPT_RESUB='P3M'
!!EXPT_RESUB_ARCHIVE_INTEGRITY='P10Y'
EXPT_RUNLEN='P18M'
!!HOST_EX='excd'
!!HOST_XC40='xcs'
MAIN_ATM_PROCX=32
MAIN_ATM_PROCY=18
MAIN_CLOCK='PT1H55M'
MAIN_HYPTHR_ATM=1
MAIN_IOS_NPROC=0
MAIN_OMPTHR_ATM=2
MAIN_RCF_PROCX=6
MAIN_RCF_PROCY=6
!!METO_ACCOUNT='climate'
!!METO_ACCOUNT_DEFAULT=true
!!METO_ACCOUNT_OTHER=''
!!METO_ARCHIVE_DUPLEX=false
!!METO_FUNDING='hccp'
!!METO_FUNDING_OTHER=''
!!METO_QUEUE='normal'
!!METO_SUBPROJECT='ukesmdev'
!!METO_SUBPROJECT_OTHER=''
MODEL_CONFIG='/mnt/lustre/a2fs-work2/work/n02/shared/tetts/opt_dfols4/d400s/d400s.mcfg'
!!NCRUN_CLOCK='PT45M'
!!NCRUN_RESUB='P10D'
!!OMP_ATM_PROCX=16
!!OMP_ATM_PROCY=16
!!OMP_HYPTHR_ATM=1
!!OMP_IOS_NPROC=0
!!OMP_OMPTHR_ATM=4
OPTCLIMTOP='/work/n02/shared/tetts/ModelOptimisation'
OPTCLIM_ARGS=' -v -v '
OPTCLIM_SET_STATUS_SCRIPT='/work/n02/shared/tetts/ModelOptimisation/OptClimVn3/scripts/set_model_status.py'
!!PE_ATM_PROCX=18
!!PE_ATM_PROCY=14
!!PE_HYPTHR_ATM=1
!!PE_IOS_NPROC=0
!!PE_OMPTHR_ATM=2
PY_ENV_SETUP='/work/n02/shared/tetts/ModelOptimisation/OptClimVn3/setup_archer2'
RUNID=False
RUNID_USR='d400s'
SITE='archer2'
!!TASK_ARCHIVE_INTEGRITY=true
!!TASK_ARCH_LOG=false
!!TASK_ARCH_WALL=false
TASK_BUILD_UM=true
TASK_HOUSEKEEP=true
TASK_JDMA=false
TASK_POSTPROC=true
TASK_PPTRANSFER=true
TASK_RECON=true
TASK_RUN=true
!!TASK_SUPERMEAN=false
TASK_TESTS=false
!!TEST_CRUN=true
!!TEST_INCS=false
!!TEST_NOOMP=true
!!TEST_NOSTASH=true
!!TEST_NRUN=true
!!TEST_OMP=true
!!TEST_PE=true
VN=13.7
