[file:$ROSE_DATA/etc/ancil/qrclim.sea]
source=/work/n02/n02/waltonj/ancil/MEDUSA/clims/by791/CHL/CHL_clim_by791_1979_2014_n96.anc

[file:$ROSE_DATA/etc/ancil/qrclim.sulpdms]
source=/work/n02/n02/waltonj/ancil/MEDUSA/clims/by791/DMS/DMS_clim_by791_1979_2014_n96.anc

[file:$ROSE_DATA/etc/ancil/qrparm.veg.canopy]
source=/work/n02/n02/waltonj/ancil/u-by791/u-by791_m01s00i218_1979-2014_time_mean_canopy_height.anc

[file:$ROSE_DATA/etc/ancil/qrparm.veg.frac]
source=/work/n02/n02/waltonj/ancil/u-by791/u-by791_m01s00i216_1979-2014_annual_timeseries_land_cover_frac.anc

[file:$ROSE_DATA/etc/ancil/qrparm.veg.lai]
source=/work/n02/n02/waltonj/ancil/u-by791/u-by791_m01s00i217_1979-2014_monthly_climatology_LAI.anc
