[command]
default=true

[env]
ATMOS=n96e
OCEAN=orca1
UM_ANCIL_DIR=${UMDIR}/ancil/atmos

[file:$ROSE_DATA/etc/ancil/qrclim.rivstor]
mode=symlink+
source=${UM_ANCIL_DIR}/${ATMOS}/${OCEAN}/rivers_trip/storage/fekete/v4/qrclim.rivstor

[file:$ROSE_DATA/etc/ancil/qrclim.sea]
mode=symlink+
source=/data/users/stephen.pring/ancils/MEDUSA/clims/by791/CHL/CHL_clim_by791_1979_2014_n96.anc

[file:$ROSE_DATA/etc/ancil/qrclim.seaice]
mode=symlink+
source=/work/n02/n02/tetts/ancil/360_day/atmos/n96e/sic_amip_n96e.anc

[file:$ROSE_DATA/etc/ancil/qrclim.sst]
mode=symlink+
source=/work/n02/n02/tetts/ancil/360_day/atmos/n96e/sst_amip_p4_n96e.anc

[file:$ROSE_DATA/etc/ancil/qrclim.sulpdms]
mode=symlink+
source=/data/users/stephen.pring/ancils/MEDUSA/clims/by791/DMS/DMS_clim_by791_1979_2014_n96.anc

[file:$ROSE_DATA/etc/ancil/qrparm.landfrac]
mode=symlink+
source=${UM_ANCIL_DIR}/${ATMOS}/${OCEAN}/land_sea_mask/etop01/v2/qrparm.landfrac

[file:$ROSE_DATA/etc/ancil/qrparm.mask]
mode=symlink+
source=${UM_ANCIL_DIR}/${ATMOS}/${OCEAN}/land_sea_mask/etop01/v2/qrparm.mask

[file:$ROSE_DATA/etc/ancil/qrparm.orog]
mode=symlink+
source=${UM_ANCIL_DIR}/${ATMOS}/${OCEAN}/orography/globe30/v6/qrparm.orog

[file:$ROSE_DATA/etc/ancil/qrparm.rivseq]
mode=symlink+
source=${UM_ANCIL_DIR}/${ATMOS}/${OCEAN}/rivers_trip/sequence/etopo5/v5/qrparm.rivseq

[file:$ROSE_DATA/etc/ancil/qrparm.soil]
mode=symlink+
source=${UM_ANCIL_DIR}/${ATMOS}/${OCEAN}/soil_parameters/hwsd_vg/v4/qrparm.soil

[file:$ROSE_DATA/etc/ancil/qrparm.soil.dust]
mode=symlink+
source=${UM_ANCIL_DIR}/${ATMOS}/${OCEAN}/soil_dust/hwsd/v4/qrparm.soil.dust

[file:$ROSE_DATA/etc/ancil/qrparm.veg.canopy]
mode=symlink+
source=/data/users/stephen.pring/ancils/u-by791/u-by791_m01s00i218_1979-2014_time_mean_canopy_height.anc

[file:$ROSE_DATA/etc/ancil/qrparm.veg.frac]
mode=symlink+
source=/data/users/stephen.pring/ancils/u-by791/u-by791_m01s00i216_1979-2014_annual_timeseries_land_cover_frac.anc

[file:$ROSE_DATA/etc/ancil/qrparm.veg.lai]
mode=symlink+
source=/data/users/stephen.pring/ancils/u-by791/u-by791_m01s00i217_1979-2014_monthly_climatology_LAI.anc
