meta=archive_and_meaning/fcm_make/postproc_2.4

[env]
config_base=fcm:moci.xm_tr
config_rev=@postproc_2.4
extract=extract
install=build
install_host=remote.cfg
model_config=um-atmos.cfg
pp_rev=postproc_2.4
pp_sources=
verify_config=verify.cfg
