[env]
config_base=fcm:moci.xm_br/dev/rosalynhatcher/postproc_2.4_archer2_jasmin_rewrite
config_rev=
pp_rev=postproc_2.4
pp_sources=fcm:moci.xm_br/dev/rosalynhatcher/postproc_2.4_archer2_jasmin_rewrite
